### ISSUE TITLE
[Feature] Inspection Grid 

### ISSUE THREAD

**Issue by tenvoltz** [UTDallasEPICS/Legacy-Housekeeping-QC#32]
**Feature Description**
Inspection Grid will display the list of all inspections, separated them into Completed and Remaining. Each inspection card will have a link to their respective Inspection Maker. The card should contain all the information listed below:
1. The location of the room
2. The team member in charge of the cleaning of that room
The card should be responsive on all screen size, and is reusable for Homepage.

**Tasks**
- [x] Wireframed the frontend for the Inspection using Figma
- [x] Create card components for completed inspection and uncompleted inspection
- [x] Create a grid to store all cards
- [x] Connect the grid to backend through API to populate the grid
