### ISSUE TITLE
[Feature] Inspection Planner

### ISSUE THREAD

**Issue by tenvoltz** [UTDallasEPICS/Legacy-Housekeeping-QC#33]
**Feature Description**
Inspection Planner will allow the user to generate a new inspection on the fly. Inspection Planner will take a list of team member and a room to create a new inspection.

**Tasks**
- [x] Wireframed the inspection planner on Figma
- [x] Develop the components for the planner
- [x] Add the inspection to database through API
