### ISSUE TITLE
[Feature] Inspection Maker

### ISSUE THREAD

**Issue by tenvoltz** [UTDallasEPICS/Legacy-Housekeeping-QC#34]
**Feature Description**
Inspection Maker will allow the user to check and uncheck various items inside a room based on their cleanliness. It will also allow the user to add comments and remove or add items. A completed inspection will not allow the user to edit the form. 

**Tasks**
- [x] Wireframed the inspection maker page in Figma
- [x] Create components for remove-able checkbox and add-able checkbox
- [x] Connect the result of the form to the database through API
