### ISSUE TITLE
[Feature] Add image functionality to Inspection Maker

### ISSUE THREAD

**Issue by tenvoltz** [UTDallasEPICS/Legacy-Housekeeping-QC#35]
**Feature Description**
For an inspection, the management team requests for the ability to add image to the inspection for record keeping purposes. The image should be stored for approximately a year. 

**Task**
- [ ] Add the image uploading and image preview to Inspection Maker frontend
- [ ] Add image compression and submission to backend
- [ ] Store the image
- [ ] Retrieve the image for completed inspection in Inspection Maker
